---
resources:
  - name: resource-source-code
    type: git
    source:
      uri: https://github.com/veeraghgoudar/devops.git
      branch: main
  - name: resource-base-container
    type: docker-image
    source:
      #email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: veeraghgoudar/concourse_base
  - name: my-timer
    type: time
    source:
      interval: 2m      

jobs:
  - name: build-and-publish-image
    public: true
    plan:
      - get: resource-source-code
      - put: resource-base-container
        params:
          build: resource-source-code
          dockerfile: resource-source-code/Dockerfile
          tag_file: resource-source-code/version.txt
      - task: check-built-image
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: veeraghgoudar/concourse_base
          run:
            path: /bin/bash
            args:
            - -exc
            - |
              echo "Checking image versions"
              ansible --version
              terraform --version
              aws --version
              
  - name: start-pipeline
    public: true
    plan:
      - get: resource-source-code
        trigger: true
      - get: my-timer
        trigger: false
      - task: print-readme.md
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu}
          run:
            path: /bin/bash
            args:
            - -exc
            - |
              echo "Printing readme.md"on
              cd resource-source-code
              ls           
              cat README.md
          inputs:
            - name: resource-source-code

  - name: get-container-image
    public: true
    plan:
      - get: resource-source-code
        trigger: true
        passed:
          - start-pipeline
      - task: check-versions-of-packages
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: veeraghgoudar/concourse_base
              tag_file: resource-source-code/version.txt
          run:
            path: /bin/bash
            args:
            - -exc
            - |
              echo "Checking image versions"
              ansible --version
              terraform --version
              aws --version

  - name: run-terraform-jobs
    public: true
    plan:
      - get: resource-source-code
        trigger: true
        passed:
          - get-container-image
      - task: run-all-terraform-commands
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: veeraghgoudar/concourse_base
              tag_file: resource-source-code/version.txt
          params:
            AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
            AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
            AWS_SESSION_TOKEN: ((AWS_SESSION_TOKEN))
            AWS_DEFAULT_REGION: ((REGION))
            TF_VAR_vpc_tag_key: ((vpc_tag_key))
            TF_VAR_vpc_tag_value: ((vpc_tag_value))
          inputs:
            - name: resource-source-code
          run:
            path: /bin/bash
            args:
            - -exc
            - |
              cd resource-source-code/terraform
              echo "******** terraform init *********"
              terraform init
              echo "******** terraform plan *********"
              terraform plan        
              echo "******** terraform apply *********"
              terraform apply -auto-approve
              echo "******** terraform output *********"
              terraform output
              echo "******** terraform destroy *********"
              terraform destroy -auto-approve            
              echo "******** End of Terraform jobs *********"   